services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: licoreria_kn
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BDD/LicoreriaBDD.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d licoreria_kn"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_URL: postgresql://postgres:admin@db:5432/licoreria_kn
      JWT_SECRET: mi_secreto_proyecto_licoreria_kn
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: "false"
      SMTP_USER: mf849040@gmail.com
      SMTP_PASS: "srfm rdnr ftkm sywr"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
    depends_on:
      - backend

volumes:
  pgdata:
