-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    cliente_id serial NOT NULL,
    nit_ci character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion_id integer,
    CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id)
);

CREATE TABLE IF NOT EXISTS public.compras
(
    compra_id serial NOT NULL,
    proveedor_id integer NOT NULL,
    numero_factura character varying(50) COLLATE pg_catalog."default",
    fecha_compra date NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    total numeric(10, 2) NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion_id integer,
    CONSTRAINT compras_pkey PRIMARY KEY (compra_id)
);

CREATE TABLE IF NOT EXISTS public.compras_detalle
(
    compra_detalle_id serial NOT NULL,
    compra_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad numeric(10, 2) NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    lote character varying(50) COLLATE pg_catalog."default",
    fecha_vencimiento date,
    CONSTRAINT compras_detalle_pkey PRIMARY KEY (compra_detalle_id)
);

CREATE TABLE IF NOT EXISTS public.inventario_movimientos
(
    movimiento_id serial NOT NULL,
    producto_id integer NOT NULL,
    tipo_movimiento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cantidad numeric(10, 2) NOT NULL,
    saldo_anterior numeric(10, 2) DEFAULT 0,
    saldo_posterior numeric(10, 2) NOT NULL,
    referencia_id integer,
    referencia_tipo character varying(50) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    fecha_movimiento timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usuario_id integer,
    CONSTRAINT inventario_movimientos_pkey PRIMARY KEY (movimiento_id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    producto_id serial NOT NULL,
    codigo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    tipo_producto character varying(50) COLLATE pg_catalog."default" NOT NULL,
    stock_actual integer NOT NULL,
    costo_unitario numeric(10, 2) NOT NULL,
    precio_venta numeric(10, 2),
    activo boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp without time zone,
    usuario_creacion_id integer,
    usuario_modificacion_id integer,
    categoria character varying(100) COLLATE pg_catalog."default",
    marca character varying(100) COLLATE pg_catalog."default",
    presentacion_ml numeric(10, 2),
    tipo_envase character varying(50) COLLATE pg_catalog."default",
    unidades_por_caja integer,
    proveedor_id integer,
    CONSTRAINT productos_pkey PRIMARY KEY (producto_id),
    CONSTRAINT productos_codigo_key UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    proveedor_id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nit character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    contacto character varying(100) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion_id integer,
    CONSTRAINT proveedores_pkey PRIMARY KEY (proveedor_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    usuario_id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    activo boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp without time zone,
    usuario_modificacion_id integer,
    CONSTRAINT usuarios_pkey PRIMARY KEY (usuario_id),
    CONSTRAINT usuarios_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    venta_id serial NOT NULL,
    cliente_id integer NOT NULL,
    fecha_venta timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    subtotal numeric(10, 2) NOT NULL,
    descuento numeric(10, 2) DEFAULT 0,
    total numeric(10, 2) NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default",
    metodo_pago character varying(50) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    usuario_creacion_id integer,
    numero_factura character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT ventas_pkey PRIMARY KEY (venta_id)
);

CREATE TABLE IF NOT EXISTS public.ventas_detalle
(
    venta_detalle_id serial NOT NULL,
    venta_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad numeric(10, 2) NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    tipo_venta character varying(10) COLLATE pg_catalog."default" DEFAULT 'unidad'::character varying,
    CONSTRAINT ventas_detalle_pkey PRIMARY KEY (venta_detalle_id)
);

ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT clientes_usuario_creacion_id_fkey FOREIGN KEY (usuario_creacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras
    ADD CONSTRAINT compras_proveedor_id_fkey FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (proveedor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras
    ADD CONSTRAINT compras_usuario_creacion_id_fkey FOREIGN KEY (usuario_creacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras
    ADD CONSTRAINT fk_compras_proveedor FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (proveedor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras_detalle
    ADD CONSTRAINT compras_detalle_compra_id_fkey FOREIGN KEY (compra_id)
    REFERENCES public.compras (compra_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.compras_detalle
    ADD CONSTRAINT compras_detalle_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (producto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras_detalle
    ADD CONSTRAINT fk_compra_detalle_compra FOREIGN KEY (compra_id)
    REFERENCES public.compras (compra_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.compras_detalle
    ADD CONSTRAINT fk_compra_detalle_producto FOREIGN KEY (producto_id)
    REFERENCES public.productos (producto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inventario_movimientos
    ADD CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id)
    REFERENCES public.productos (producto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_inventario_producto
    ON public.inventario_movimientos(producto_id);


ALTER TABLE IF EXISTS public.inventario_movimientos
    ADD CONSTRAINT inventario_movimientos_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (producto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_inventario_producto
    ON public.inventario_movimientos(producto_id);


ALTER TABLE IF EXISTS public.inventario_movimientos
    ADD CONSTRAINT inventario_movimientos_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT fk_producto_proveedor FOREIGN KEY (proveedor_id)
    REFERENCES public.proveedores (proveedor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT productos_usuario_creacion_id_fkey FOREIGN KEY (usuario_creacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT productos_usuario_modificacion_id_fkey FOREIGN KEY (usuario_modificacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.proveedores
    ADD CONSTRAINT proveedores_usuario_creacion_id_fkey FOREIGN KEY (usuario_creacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_usuario_modificacion_id_fkey FOREIGN KEY (usuario_modificacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT fk_ventas_cliente FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT ventas_usuario_creacion_id_fkey FOREIGN KEY (usuario_creacion_id)
    REFERENCES public.usuarios (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas_detalle
    ADD CONSTRAINT fk_venta_detalle_venta FOREIGN KEY (venta_id)
    REFERENCES public.ventas (venta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ventas_detalle
    ADD CONSTRAINT ventas_detalle_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.productos (producto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_venta_detalle_producto
    ON public.ventas_detalle(producto_id);


ALTER TABLE IF EXISTS public.ventas_detalle
    ADD CONSTRAINT ventas_detalle_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.ventas (venta_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;